version: '3.8'

services:
  publisher_service:
    container_name: transaction_publisher_service
    build:
      context: .
      dockerfile: build/docker/publisher_service/Dockerfile
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - nats
    env_file:
      .env

  consumer_service:
    container_name: transaction_consumer_service
    build:
      context: .
      dockerfile: build/docker/consumer_service/Dockerfile
    restart: unless-stopped
    links:
      - db
    depends_on:
      - db
      - nats

  db:
    container_name: user_transaction_db
    build:
      context: build/docker/db
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgres/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      .env

  nats:
    image: nats:latest
    restart: on-failure
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--js", "--jetstream"]

volumes:
  pg_data: